### ISSUE TITLE
Filter with int default (0) value.

### ISSUE THREAD

**Issue by p1eXu5** [AngelMunoz/Mondocks#34]
With `options.DefaultIgnoreCondition <- JsonIgnoreCondition.WhenWritingDefault` settings expression like this:

```fs
find "users" {
    filter {| age = {| ``$gt`` = 0 |} |}
    limit 5
}
```

is producing this json:

```json
{"find":"users","filter":{"age":{}},"limit":{"$numberInt":"5"}}
```

and we get no documents.

But with `options.DefaultIgnoreCondition <- JsonIgnoreCondition.WhenWritingNull`:

```json
{"find":"users","filter":{"age":{"$gt":{"$numberInt":"0"}}},"limit":{"$numberInt":"5"}}
```
and filter works as expected.

I suppose you should replace the settings in default serializer options.

Affected version: Mondocs.Net (0.4.8)

**Comment by AngelMunoz** [comment]
Hey there thanks for the notice! 
I agree, we should get this one changed

**Comment by AngelMunoz** [comment]
There was an issue related to this when you wanted to actually use null values in queries I think I made the change to default value due to this https://github.com/AngelMunoz/Mondocks/issues/32

But I think going back to when writing null is a good call out

I might need to re-visit this library later because this serialization stuff is quite flakey

**Comment by AngelMunoz** [comment]
v0.5.0 is out and we went back to when writing null, please give it a shot and let me know if something is not so right
