### ISSUE TITLE
Serialization errors with `FindResult`, `DeleteResult` on dotnet

### ISSUE THREAD

**Issue by moonshxne** [AngelMunoz/Mondocks#36]
Running the examples in `samples/Commands` fails because the MongoDB driver expects certain fields that don't exist in a `FindResult<'T>` or a `UpdateResult` to actually exist.

On my end, I can confirm that simply doing

```fs
[<BsonIgnoreExtraElements>]
type FindResult<'T> = { cursor: Cursor<'T>; ok: float }
```

resolves this (because Mongo also returns the `operationTime` field). 

However, it's not just this one simple fix; the update command still fails because of the same issue. My conclusion is that we'll have to add this attribute to **all** of the types in Mondocks.Net's `Types.fs`; it follows that it might not make sense to share the types between `Mondocks.Net` and `Mondocks.Fable`?

Finally, a small feature request/design question: what determines which fields make it into the result structs? It would be nice, for instance, to also be able to also inspect the `upserted` items of an `UpdateResult`. See [output reference here](https://www.mongodb.com/docs/manual/reference/command/update/#output).

**Comment by AngelMunoz** [comment]
Hey there, I need some time to check this but thanks for the primer information. 

I haven't had a chance to use mongo in a while, so I left this library to get some age... that's on me!

> it follows that it might not make sense to share the types between Mondocks.Net and Mondocks.Fable?

It kind of makes sense if you ever share code but to be honest I guess on the fable side there are other mongo specific libraries that could be annotated to have a better DX I guess it is up to consideration if the fable target is really needed.

> Finally, a small feature request/design question: what determines which fields make it into the result structs?

I don't particularly remember why... to be honest, I'm not married to anything so we can make changes in this area.

> See [output reference here](https://www.mongodb.com/docs/manual/reference/command/update/#output).

Oh, nice I wasn't aware of this, this could help to fix up these kinds of issues.



On a side note, are you interested in making these changes? I'd gladly accept contributions as it might take me a while to get to work on this personally; we can push a new dotnet package rather than a fable one while I think about that one.

**Comment by moonshxne** [comment]
Hey there, thanks for replying! I didn't create a PR because I wasn't super sure how you wanted to deal with code sharing. Can't do it today, but I'll add the types to Mondocks.Net with [<BsonIgnoreExtraElements>] and go from there?

**Comment by AngelMunoz** [comment]
Yes, there's more utility in the dotnet version than the fable one, in any case we can revisit the fable package at some point if we need to but that's not a concern for now

**Comment by AngelMunoz** [comment]
I just merged the PR I'll try to put out a release later today in case you're blocked!

Thank you very much for this contribution!

**Comment by AngelMunoz** [comment]
https://www.nuget.org/packages/Mondocks.Net/0.6.0 published, we just need to wait for NuGet to index and list the package!

once again thank you!
